import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import {
  Container,
  Nav,
  Navbar,
  NavbarBrand,
  NavbarCollapse,
  NavbarToggle,
  NavLink,
} from "react-bootstrap";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar expand="sm" className="bg-body-tertiary">
          <Container>
            <NavbarBrand>ABI Market</NavbarBrand>
            <NavbarToggle aria-controls="basic-navbar-nav" />
            <NavbarCollapse>
              <Nav className="me-auto">
                <NavLink>
                  <Link href={"/"} className="text-black">
                    Home
                  </Link>
                </NavLink>
                <NavLink>
                  <Link href={"/market"} className="text-black">
                    Market
                  </Link>
                </NavLink>
              </Nav>
            </NavbarCollapse>
          </Container>
        </Navbar>
        {children}
      </body>
    </html>
  );
}
